spring:
  application.name: github-analytics

  cloud.stream.bindings.input.destination: messages

  jpa:
    database: MYSQL
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server.port: ${PORT:8081}
endpoints.sensitive: false